# Generated by Django 4.0.4 on 2022-05-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('booking_time', models.DateTimeField()),
                ('people', models.IntegerField()),
                ('req', models.TextField()),
            ],
        ),
    ]
